### ISSUE TITLE
Neocities Hosting Problem

### ISSUE THREAD

**Issue by cheeriko** [charadex-team/charadex-v1.0#3]
Neocities no longer allows imports from 3rd party sites via JS. I wasn't privy to this because my account predates the changes OR because I've had premium in the past.

**Possible Options:** 
- You can pay for 1 month premium and see if it works (I have all premium features and haven't paid since 2 years ago so?) 
- Host on a public repo on Github and deploy via pages

If anyone knows of another place to host, that would be fantastic.

**Comment by cheeriko** [comment]
New info on Neocities: New and free accounts will be restricted from using 3rd party sites to retrieve data. You can grab a subscription to bypass this apparently (I've not tested myself.)

Source: https://github.com/neocities/neocities/issues/484

**Comment by cheeriko** [comment]
Tagging from issue in old repo: @Mellocide @Magicalartprince @HaloDevil @Keppop @KhaoticKoda @HaloOfHope

**Comment by cheeriko** [comment]
Also adding that if you're in **_dire_** need of showing your masterlist, [Quickdex](https://charadex.com/quickdex/) can make that happen until a permanent fix is found!

**Comment by Mellocide** [comment]
HELLO THERE!!! I was given a github+netlify setup tutorial on Toyhouse by Avistella in my help thread - my site is now up and functioning, so I've confirmed **_it works_** and I'd like to share it with you!

https://toyhou.se/~forums/14421.help-questions/483533.netlify-charadex-tutorial-solved?page=0

**Comment by cheeriko** [comment]
Adding link for a quick Netilfy tutorial, thanks to Avistella on Toyhou.se!

[Tutorial Here](https://toyhou.se/~forums/14421.help-questions/483533.netlify-charadex-tutorial-solved?page=0#post-7480675)
